//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMP_IL_Guard.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAMP_IL_Guard.Languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me the agreement again if it ever changes.
        /// </summary>
        internal static string ACAgain {
            get {
                return ResourceManager.GetString("ACAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ACClose {
            get {
                return ResourceManager.GetString("ACClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ACContinue {
            get {
                return ResourceManager.GetString("ACContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-MP Guard Service Agreement.
        /// </summary>
        internal static string ACHeader {
            get {
                return ResourceManager.GetString("ACHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read, understood and accepted the agreement.
        /// </summary>
        internal static string ACRead {
            get {
                return ResourceManager.GetString("ACRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string ACSource {
            get {
                return ResourceManager.GetString("ACSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to activate the program you must accept the following agreement:.
        /// </summary>
        internal static string ACText {
            get {
                return ResourceManager.GetString("ACText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change nickname.
        /// </summary>
        internal static string ButtonChangeNick {
            get {
                return ResourceManager.GetString("ButtonChangeNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string ButtonConnect {
            get {
                return ResourceManager.GetString("ButtonConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string ButtonDisconnect {
            get {
                return ResourceManager.GetString("ButtonDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string ButtonPlay {
            get {
                return ResourceManager.GetString("ButtonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFG file found..
        /// </summary>
        internal static string CDCFG {
            get {
                return ResourceManager.GetString("CDCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat detection is working..
        /// </summary>
        internal static string CDCheat {
            get {
                return ResourceManager.GetString("CDCheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working with My Documents....
        /// </summary>
        internal static string CDDocuments {
            get {
                return ResourceManager.GetString("CDDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect version detected..
        /// </summary>
        internal static string CDIncorrectVersion {
            get {
                return ResourceManager.GetString("CDIncorrectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet is working....
        /// </summary>
        internal static string CDInternet {
            get {
                return ResourceManager.GetString("CDInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists have successfully been updated....
        /// </summary>
        internal static string CDLists {
            get {
                return ResourceManager.GetString("CDLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string CDLoading {
            get {
                return ResourceManager.GetString("CDLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname has been found....
        /// </summary>
        internal static string CDNickname {
            get {
                return ResourceManager.GetString("CDNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for GTASA directory....
        /// </summary>
        internal static string CDPath {
            get {
                return ResourceManager.GetString("CDPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry is working....
        /// </summary>
        internal static string CDRegistry {
            get {
                return ResourceManager.GetString("CDRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server reading is comleted....
        /// </summary>
        internal static string CDServers {
            get {
                return ResourceManager.GetString("CDServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version detected: .
        /// </summary>
        internal static string CDVersion {
            get {
                return ResourceManager.GetString("CDVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate cleo mods.
        /// </summary>
        internal static string CLActive {
            get {
                return ResourceManager.GetString("CLActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CLButtonCancel {
            get {
                return ResourceManager.GetString("CLButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string CLButtonDo {
            get {
                return ResourceManager.GetString("CLButtonDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel cleo mods.
        /// </summary>
        internal static string CLDeactive {
            get {
                return ResourceManager.GetString("CLDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleo Mod.
        /// </summary>
        internal static string CLHeader {
            get {
                return ResourceManager.GetString("CLHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can choose whether to use cleo mods or not, because they are not allowed in some of the servers..
        /// </summary>
        internal static string CLText {
            get {
                return ResourceManager.GetString("CLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CNButtonCancel {
            get {
                return ResourceManager.GetString("CNButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string CNButtonChange {
            get {
                return ResourceManager.GetString("CNButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change nickname.
        /// </summary>
        internal static string CNHeader {
            get {
                return ResourceManager.GetString("CNHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new nickname here:
        ///(If SA-MP window is active, you&apos;ll need to close and reopen it for the name to be updated).
        /// </summary>
        internal static string CNText {
            get {
                return ResourceManager.GetString("CNText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string EButtonClose {
            get {
                return ResourceManager.GetString("EButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-MP Guard
        ///Application Error:.
        /// </summary>
        internal static string EError {
            get {
                return ResourceManager.GetString("EError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string EHeader {
            get {
                return ResourceManager.GetString("EHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-MP Guard is already active..
        /// </summary>
        internal static string ErrorAlreadyActive {
            get {
                return ResourceManager.GetString("ErrorAlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-MP is already active on this computer..
        /// </summary>
        internal static string ErrorAlreadySamp {
            get {
                return ResourceManager.GetString("ErrorAlreadySamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleo mods folder is already exists. Have you tried to install cleo mod after disabling it in the program?.
        /// </summary>
        internal static string ErrorCleo1 {
            get {
                return ResourceManager.GetString("ErrorCleo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find cleo mods backup folder..
        /// </summary>
        internal static string ErrorCleo2 {
            get {
                return ResourceManager.GetString("ErrorCleo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleo mods backup folder is already exists, it is probably an error occurs by the program..
        /// </summary>
        internal static string ErrorCleo3 {
            get {
                return ResourceManager.GetString("ErrorCleo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the folder of cleo mods..
        /// </summary>
        internal static string ErrorCleo4 {
            get {
                return ResourceManager.GetString("ErrorCleo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t change your nickname as long as the SA-MP window is active. Please close it..
        /// </summary>
        internal static string ErrorCNSamp {
            get {
                return ResourceManager.GetString("ErrorCNSamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize failed. Error code:.
        /// </summary>
        internal static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting operation have been failed:.
        /// </summary>
        internal static string ErrorDisconnectFailed {
            get {
                return ResourceManager.GetString("ErrorDisconnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create file files, probably because there is no permission. Try restarting the program as administrator..
        /// </summary>
        internal static string ErrorFiles {
            get {
                return ResourceManager.GetString("ErrorFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t connect while your GTA SA game is running. Close it, connect with SA-MP Guard, and then start it again..
        /// </summary>
        internal static string ErrorGameActive {
            get {
                return ResourceManager.GetString("ErrorGameActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-MP Guard doesn&apos;t recognize GTA San Andreas &amp; SA-MP in this computer..
        /// </summary>
        internal static string ErrorGTA {
            get {
                return ResourceManager.GetString("ErrorGTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name defined in the program is not equal to the name in your SA-MP client. Please match them..
        /// </summary>
        internal static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to the internet. Please make sure that the computer have an working network connection..
        /// </summary>
        internal static string ErrorNet {
            get {
                return ResourceManager.GetString("ErrorNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We haven&apos;t found any cleo mods installed on your computer..
        /// </summary>
        internal static string ErrorNoCleo {
            get {
                return ResourceManager.GetString("ErrorNoCleo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any processes..
        /// </summary>
        internal static string ErrorPrc {
            get {
                return ResourceManager.GetString("ErrorPrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check out your processes..
        /// </summary>
        internal static string ErrorPrcTrace {
            get {
                return ResourceManager.GetString("ErrorPrcTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieving information from the server have been failed. This may occur when the server is turning off or removing SA-MP Guard..
        /// </summary>
        internal static string ErrorRecieve {
            get {
                return ResourceManager.GetString("ErrorRecieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file sa-mp.cfg isn&apos;t found, the program can not continue..
        /// </summary>
        internal static string ErrorSAMPCFG {
            get {
                return ResourceManager.GetString("ErrorSAMPCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program wasn&apos;t able to send information to the server:.
        /// </summary>
        internal static string ErrorSend {
            get {
                return ResourceManager.GetString("ErrorSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information have been failed to be sent:.
        /// </summary>
        internal static string ErrorSent {
            get {
                return ResourceManager.GetString("ErrorSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a server from the list..
        /// </summary>
        internal static string ErrorServerSelect {
            get {
                return ResourceManager.GetString("ErrorServerSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your SA-MP Guard version doesn&apos;t match to the newest one.\nYour version: {OWN}\nThe server version: {NEW}.
        /// </summary>
        internal static string ErrorVersion {
            get {
                return ResourceManager.GetString("ErrorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been automatically disconnected for being out of the game for the last two minutes..
        /// </summary>
        internal static string MsgAutoDisconnect {
            get {
                return ResourceManager.GetString("MsgAutoDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleo mods have been turned off..
        /// </summary>
        internal static string MsgCleoOff {
            get {
                return ResourceManager.GetString("MsgCleoOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleo mods have been turned on..
        /// </summary>
        internal static string MsgCleoOn {
            get {
                return ResourceManager.GetString("MsgCleoOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your nickname have been changed..
        /// </summary>
        internal static string MsgCN {
            get {
                return ResourceManager.GetString("MsgCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to X:Y with client ID Z..
        /// </summary>
        internal static string MsgConnected {
            get {
                return ResourceManager.GetString("MsgConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to .
        /// </summary>
        internal static string MsgConnecting {
            get {
                return ResourceManager.GetString("MsgConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to X:Y have been failed: the server is off, or it is lagged or it isn&apos;t using SA-MP Guard..
        /// </summary>
        internal static string MsgConnectionFailed {
            get {
                return ResourceManager.GetString("MsgConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting....
        /// </summary>
        internal static string MsgDisconnecting {
            get {
                return ResourceManager.GetString("MsgDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server you were in have just turned off the connection..
        /// </summary>
        internal static string MsgForceDisconnect {
            get {
                return ResourceManager.GetString("MsgForceDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system doesn&apos;t recognize any cheat or hacking files on your computer..
        /// </summary>
        internal static string MsgNoCheats {
            get {
                return ResourceManager.GetString("MsgNoCheats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline..
        /// </summary>
        internal static string MsgOffline {
            get {
                return ResourceManager.GetString("MsgOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, we&apos;ve found out that one or more of your running applications seems to be a cheat or hack..
        /// </summary>
        internal static string MsgPrcCheats {
            get {
                return ResourceManager.GetString("MsgPrcCheats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string NVButtonClose {
            get {
                return ResourceManager.GetString("NVButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version.
        /// </summary>
        internal static string NVHeader {
            get {
                return ResourceManager.GetString("NVHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To download, please enter the link below:.
        /// </summary>
        internal static string NVLink {
            get {
                return ResourceManager.GetString("NVLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-MP Guard
        ///New version:.
        /// </summary>
        internal static string NVMessage {
            get {
                return ResourceManager.GetString("NVMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest version:.
        /// </summary>
        internal static string NVNewest {
            get {
                return ResourceManager.GetString("NVNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version:.
        /// </summary>
        internal static string NVOwn {
            get {
                return ResourceManager.GetString("NVOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will have to download the new version in order to use SA-MP Guard..
        /// </summary>
        internal static string NVWarning {
            get {
                return ResourceManager.GetString("NVWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string RCButtonCancel {
            get {
                return ResourceManager.GetString("RCButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string RCButtonOpenFolder {
            get {
                return ResourceManager.GetString("RCButtonOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all files.
        /// </summary>
        internal static string RCButtonRemove {
            get {
                return ResourceManager.GetString("RCButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I choose to remove the files and I know that I will maybe not be able to return them.
        /// </summary>
        internal static string RCCheckBox {
            get {
                return ResourceManager.GetString("RCCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File details.
        /// </summary>
        internal static string RCDetails {
            get {
                return ResourceManager.GetString("RCDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name:.
        /// </summary>
        internal static string RCFileName {
            get {
                return ResourceManager.GetString("RCFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove cheats.
        /// </summary>
        internal static string RCHeader {
            get {
                return ResourceManager.GetString("RCHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following files have been recognized as connected to cheats or hacks, and they should be deleted:.
        /// </summary>
        internal static string RCMessage {
            get {
                return ResourceManager.GetString("RCMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        internal static string RCPath {
            get {
                return ResourceManager.GetString("RCPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string RTL {
            get {
                return ResourceManager.GetString("RTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ToolStripAbout {
            get {
                return ResourceManager.GetString("ToolStripAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheats Remove.
        /// </summary>
        internal static string ToolStripCheats {
            get {
                return ResourceManager.GetString("ToolStripCheats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleo.
        /// </summary>
        internal static string ToolStripCleo {
            get {
                return ResourceManager.GetString("ToolStripCleo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        internal static string ToolStripMinimize {
            get {
                return ResourceManager.GetString("ToolStripMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string ToolStripQuit {
            get {
                return ResourceManager.GetString("ToolStripQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-MP Guard - Official Site.
        /// </summary>
        internal static string ToolStripSite {
            get {
                return ResourceManager.GetString("ToolStripSite", resourceCulture);
            }
        }
    }
}
