//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMP_IL_Guard.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Hebrew {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hebrew() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAMP_IL_Guard.Languages.Hebrew", typeof(Hebrew).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצג לי שוב את ההסכם במידה והוא ישתנה בעתיד.
        /// </summary>
        internal static string ACAgain {
            get {
                return ResourceManager.GetString("ACAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סגור.
        /// </summary>
        internal static string ACClose {
            get {
                return ResourceManager.GetString("ACClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשך.
        /// </summary>
        internal static string ACContinue {
            get {
                return ResourceManager.GetString("ACContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אישור שימוש במערכת SA-MP Guard.
        /// </summary>
        internal static string ACHeader {
            get {
                return ResourceManager.GetString("ACHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קראתי, הבנתי ואני מאשר את ההסכם.
        /// </summary>
        internal static string ACRead {
            get {
                return ResourceManager.GetString("ACRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקור.
        /// </summary>
        internal static string ACSource {
            get {
                return ResourceManager.GetString("ACSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to על מנת להפעיל את התוכנה, עליך לאשר את ההסכם הבא:.
        /// </summary>
        internal static string ACText {
            get {
                return ResourceManager.GetString("ACText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שנה כינוי.
        /// </summary>
        internal static string ButtonChangeNick {
            get {
                return ResourceManager.GetString("ButtonChangeNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחבר לשרת.
        /// </summary>
        internal static string ButtonConnect {
            get {
                return ResourceManager.GetString("ButtonConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניתוק.
        /// </summary>
        internal static string ButtonDisconnect {
            get {
                return ResourceManager.GetString("ButtonDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחל לשחק.
        /// </summary>
        internal static string ButtonPlay {
            get {
                return ResourceManager.GetString("ButtonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מציאת קובץ CFG הושלמה..
        /// </summary>
        internal static string CDCFG {
            get {
                return ResourceManager.GetString("CDCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מציאת צ&apos;יטים עובדת. העבודה הושלמה..
        /// </summary>
        internal static string CDCheat {
            get {
                return ResourceManager.GetString("CDCheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כתיבה במסמכים שלי עובדת....
        /// </summary>
        internal static string CDDocuments {
            get {
                return ResourceManager.GetString("CDDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גרסה לא תקינה..
        /// </summary>
        internal static string CDIncorrectVersion {
            get {
                return ResourceManager.GetString("CDIncorrectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קריאה מהאינטרנט עובדת....
        /// </summary>
        internal static string CDInternet {
            get {
                return ResourceManager.GetString("CDInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשימות הוגדרו בהצלחה....
        /// </summary>
        internal static string CDLists {
            get {
                return ResourceManager.GetString("CDLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחילת טעינה....
        /// </summary>
        internal static string CDLoading {
            get {
                return ResourceManager.GetString("CDLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כינוי נמצא....
        /// </summary>
        internal static string CDNickname {
            get {
                return ResourceManager.GetString("CDNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מוצא את תיקיית GTASA....
        /// </summary>
        internal static string CDPath {
            get {
                return ResourceManager.GetString("CDPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כתיבה וקריאה ברגיסטרי עובדים....
        /// </summary>
        internal static string CDRegistry {
            get {
                return ResourceManager.GetString("CDRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קריאת שרתים הושלמה....
        /// </summary>
        internal static string CDServers {
            get {
                return ResourceManager.GetString("CDServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נקראה גרסה: .
        /// </summary>
        internal static string CDVersion {
            get {
                return ResourceManager.GetString("CDVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפעל מוד Cleo.
        /// </summary>
        internal static string CLActive {
            get {
                return ResourceManager.GetString("CLActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביטול.
        /// </summary>
        internal static string CLButtonCancel {
            get {
                return ResourceManager.GetString("CLButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בצע.
        /// </summary>
        internal static string CLButtonDo {
            get {
                return ResourceManager.GetString("CLButtonDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בטל מוד Cleo.
        /// </summary>
        internal static string CLDeactive {
            get {
                return ResourceManager.GetString("CLDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleo מוד.
        /// </summary>
        internal static string CLHeader {
            get {
                return ResourceManager.GetString("CLHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מכאן תוכלו לבחור האם להפעיל מודים מסוג Cleo או לא, מכיוון שהם אסורים בחלק מהשרתים..
        /// </summary>
        internal static string CLText {
            get {
                return ResourceManager.GetString("CLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביטול.
        /// </summary>
        internal static string CNButtonCancel {
            get {
                return ResourceManager.GetString("CNButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שינוי.
        /// </summary>
        internal static string CNButtonChange {
            get {
                return ResourceManager.GetString("CNButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שינוי כינוי.
        /// </summary>
        internal static string CNHeader {
            get {
                return ResourceManager.GetString("CNHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקלד כאן את הכינוי החדש שלך:
        ///(אם תוכנת SA-MP פתוחה, הכינוי יתעדכן אחרי שתפעיל אותה מחדש).
        /// </summary>
        internal static string CNText {
            get {
                return ResourceManager.GetString("CNText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סגור.
        /// </summary>
        internal static string EButtonClose {
            get {
                return ResourceManager.GetString("EButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-MP Guard
        ///שגיאת תוכנה:.
        /// </summary>
        internal static string EError {
            get {
                return ResourceManager.GetString("EError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שגיאה.
        /// </summary>
        internal static string EHeader {
            get {
                return ResourceManager.GetString("EHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-MP Guard כבר פעילה במחשב שלך..
        /// </summary>
        internal static string ErrorAlreadyActive {
            get {
                return ResourceManager.GetString("ErrorAlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-MP כבר פעיל במחשב..
        /// </summary>
        internal static string ErrorAlreadySamp {
            get {
                return ResourceManager.GetString("ErrorAlreadySamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תיקיית מוד Cleo כבר קיימת. האם התקנת מוד מסוג Cleo אחרי שביטלת אותו דרך התוכנה? יש ליצור סדר בתיקיות..
        /// </summary>
        internal static string ErrorCleo1 {
            get {
                return ResourceManager.GetString("ErrorCleo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצאה תיקיית גיבוי למודי Cleo..
        /// </summary>
        internal static string ErrorCleo2 {
            get {
                return ResourceManager.GetString("ErrorCleo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תיקיית גיבוי כבר קיימת, ככל הנראה חלה בעיה עם שימוש בתוכנה. יש ליצור סדר בתיקיות..
        /// </summary>
        internal static string ErrorCleo3 {
            get {
                return ResourceManager.GetString("ErrorCleo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצאה תיקיית מודים של Cleo..
        /// </summary>
        internal static string ErrorCleo4 {
            get {
                return ResourceManager.GetString("ErrorCleo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לשנות כינוי כשהחלון של SA-MP פתוח. נא לסגור אותו קודם..
        /// </summary>
        internal static string ErrorCNSamp {
            get {
                return ResourceManager.GetString("ErrorCNSamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טעינת התוכנה נכשלה. קוד הבעיה:.
        /// </summary>
        internal static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ההתנתקות נכשלה. מידע נוסף:.
        /// </summary>
        internal static string ErrorDisconnectFailed {
            get {
                return ResourceManager.GetString("ErrorDisconnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין הרשאה לכתיבה בקבצים במחשב זה. נסה לפתוח כמנהל..
        /// </summary>
        internal static string ErrorFiles {
            get {
                return ResourceManager.GetString("ErrorFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן להתחבר כאשר המשחק GTA SA פתוח. סגור אותו, התחבר עם SA-MP Guard ואז פתח אותו מחדש..
        /// </summary>
        internal static string ErrorGameActive {
            get {
                return ResourceManager.GetString("ErrorGameActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-MP Guard לא מזהה את GTA San Andreas &amp; SA-MP במחשב זה..
        /// </summary>
        internal static string ErrorGTA {
            get {
                return ResourceManager.GetString("ErrorGTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכינוי שלך בתוכנה וב-SA-MP אינם זהים. הפוך אותם לשווים ונסה שוב..
        /// </summary>
        internal static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן ליצור קשר עם הרשת. וודא שהמחשב מחובר לאינטרנט..
        /// </summary>
        internal static string ErrorNet {
            get {
                return ResourceManager.GetString("ErrorNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצאו מודים מסוג Cleo במחשב שלך..
        /// </summary>
        internal static string ErrorNoCleo {
            get {
                return ResourceManager.GetString("ErrorNoCleo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן להשתמש בתהליכים שבמחשב זה..
        /// </summary>
        internal static string ErrorPrc {
            get {
                return ResourceManager.GetString("ErrorPrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כשלון במעקב אחר תהליכים. מידע נוסף:.
        /// </summary>
        internal static string ErrorPrcTrace {
            get {
                return ResourceManager.GetString("ErrorPrcTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קבלת מידע מהשרת נכשלה. הסיבה יכולה להיות שהוא נפל או שאינו משתמש יותר ב-SA-MP Guard..
        /// </summary>
        internal static string ErrorRecieve {
            get {
                return ResourceManager.GetString("ErrorRecieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקובץ sa-mp.cfg לא נמצא ולכן לא ניתן להמשיך..
        /// </summary>
        internal static string ErrorSAMPCFG {
            get {
                return ResourceManager.GetString("ErrorSAMPCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יציאת מידע נכשלה. מידע נוסף:.
        /// </summary>
        internal static string ErrorSend {
            get {
                return ResourceManager.GetString("ErrorSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שליחת מידע משחק אל השרת נכשלה. מידע נוסף:.
        /// </summary>
        internal static string ErrorSent {
            get {
                return ResourceManager.GetString("ErrorSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עליך לבחור שרת להתחברות..
        /// </summary>
        internal static string ErrorServerSelect {
            get {
                return ResourceManager.GetString("ErrorServerSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גרסת SA-MP Guard של השרת אינה תואמת לזו שלך.\nהגרסה שלך: {OWN}\nהגרסה של השרת: {NEW}.
        /// </summary>
        internal static string ErrorVersion {
            get {
                return ResourceManager.GetString("ErrorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נותקת אוטומטית מהשרת מאחר ולא שיחקת בו 2 דקות..
        /// </summary>
        internal static string MsgAutoDisconnect {
            get {
                return ResourceManager.GetString("MsgAutoDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודים מסוג Cleo בוטלו..
        /// </summary>
        internal static string MsgCleoOff {
            get {
                return ResourceManager.GetString("MsgCleoOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודים מסוג Cleo הוחזרו..
        /// </summary>
        internal static string MsgCleoOn {
            get {
                return ResourceManager.GetString("MsgCleoOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכינוי שונה בהצלחה..
        /// </summary>
        internal static string MsgCN {
            get {
                return ResourceManager.GetString("MsgCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחובר לשרת X:Y במספר הסידורי Z..
        /// </summary>
        internal static string MsgConnected {
            get {
                return ResourceManager.GetString("MsgConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מתחבר לשרת .
        /// </summary>
        internal static string MsgConnecting {
            get {
                return ResourceManager.GetString("MsgConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ההתחברות לשרת X:Y נכשלה: השרת נפל או שהוא בלאגים או שאינו משתמש ב-SA-MP Guard..
        /// </summary>
        internal static string MsgConnectionFailed {
            get {
                return ResourceManager.GetString("MsgConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מתנתק....
        /// </summary>
        internal static string MsgDisconnecting {
            get {
                return ResourceManager.GetString("MsgDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השרת שאליו חוברת לאחרונה ניתק אותך מהמערכת..
        /// </summary>
        internal static string MsgForceDisconnect {
            get {
                return ResourceManager.GetString("MsgForceDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המערכת לא מצאה קבצי צ&apos;יטים פעילים במחשב שלך..
        /// </summary>
        internal static string MsgNoCheats {
            get {
                return ResourceManager.GetString("MsgNoCheats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא מחובר..
        /// </summary>
        internal static string MsgOffline {
            get {
                return ResourceManager.GetString("MsgOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עם זאת, המערכת מזהה שיש תהליך פתוח שאחראי לצ&apos;יטים..
        /// </summary>
        internal static string MsgPrcCheats {
            get {
                return ResourceManager.GetString("MsgPrcCheats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יציאה.
        /// </summary>
        internal static string NVButtonClose {
            get {
                return ResourceManager.GetString("NVButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גרסה חדשה.
        /// </summary>
        internal static string NVHeader {
            get {
                return ResourceManager.GetString("NVHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to להורדה, יש להכנס לכתובת הבאה:.
        /// </summary>
        internal static string NVLink {
            get {
                return ResourceManager.GetString("NVLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-MP Guard
        ///גרסה חדשה:.
        /// </summary>
        internal static string NVMessage {
            get {
                return ResourceManager.GetString("NVMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגרסה הכי חדשה:.
        /// </summary>
        internal static string NVNewest {
            get {
                return ResourceManager.GetString("NVNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגרסה שיש לך:.
        /// </summary>
        internal static string NVOwn {
            get {
                return ResourceManager.GetString("NVOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חובה להשתמש בגרסה החדשה כדי להפעיל את התוכנה..
        /// </summary>
        internal static string NVWarning {
            get {
                return ResourceManager.GetString("NVWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביטול.
        /// </summary>
        internal static string RCButtonCancel {
            get {
                return ResourceManager.GetString("RCButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פתח מיקום תיקיה.
        /// </summary>
        internal static string RCButtonOpenFolder {
            get {
                return ResourceManager.GetString("RCButtonOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחק את כל הקבצים.
        /// </summary>
        internal static string RCButtonRemove {
            get {
                return ResourceManager.GetString("RCButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אני מאשר את מחיקת הקבצים לצמיתות ואני יודע שיכול להיות שלא יהיה ניתן להחזיר אותם..
        /// </summary>
        internal static string RCCheckBox {
            get {
                return ResourceManager.GetString("RCCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרטי קובץ.
        /// </summary>
        internal static string RCDetails {
            get {
                return ResourceManager.GetString("RCDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם הקובץ:.
        /// </summary>
        internal static string RCFileName {
            get {
                return ResourceManager.GetString("RCFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסרת צ&apos;יטים.
        /// </summary>
        internal static string RCHeader {
            get {
                return ResourceManager.GetString("RCHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקבצים הבאים זוהו כקשורים לצ&apos;יטים, ועליהם להמחק על מנת שלא תזוהה כצ&apos;יטר:.
        /// </summary>
        internal static string RCMessage {
            get {
                return ResourceManager.GetString("RCMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מיקום:.
        /// </summary>
        internal static string RCPath {
            get {
                return ResourceManager.GetString("RCPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string RTL {
            get {
                return ResourceManager.GetString("RTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אודות.
        /// </summary>
        internal static string ToolStripAbout {
            get {
                return ResourceManager.GetString("ToolStripAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסרת צ&apos;יטים.
        /// </summary>
        internal static string ToolStripCheats {
            get {
                return ResourceManager.GetString("ToolStripCheats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleo.
        /// </summary>
        internal static string ToolStripCleo {
            get {
                return ResourceManager.GetString("ToolStripCleo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מזער.
        /// </summary>
        internal static string ToolStripMinimize {
            get {
                return ResourceManager.GetString("ToolStripMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יציאה.
        /// </summary>
        internal static string ToolStripQuit {
            get {
                return ResourceManager.GetString("ToolStripQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-MP Guard - אתר המערכת.
        /// </summary>
        internal static string ToolStripSite {
            get {
                return ResourceManager.GetString("ToolStripSite", resourceCulture);
            }
        }
    }
}
